# name: Clang-Format & trash files
name: Clang-Format

on:
  push:
   branches: [ "master", "dev" ]
  pull_request:
   branches: [ "master", "dev" ]
  workflow_dispatch:

jobs:
  clang-format-and-trash-files:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/louismoretti/42sh/42sh-ci:latest

    steps:
    - uses: actions/checkout@v4

    - name: GIT Setup
      run: git config --global --add safe.directory '*'

    # - name: Check for trash files
    #   shell: bash
    #   run: |
    #     ALLOWED="(Makefile\.am|^src/.+\.[ch]|^tests/.+(\.([ch]|py|sh)|tests_files/.+|Dockerfile)|^\.gitignore|^README(\.md)?|^.clang-(format|tidy)|^\.github/workflows/.+\.yml|^configure.ac)$"
    #     EXIT_CODE=0
    #     for file in $(git ls-files | sed "s|\./||"); do
    #         if [[ ! "$file" =~ $ALLOWED ]]; then
    #             echo "[TRASH FOUND] : $file"
    #             EXIT_CODE=1
    #         fi
    #     done
    #     exit $EXIT_CODE

    # - name: Install clang-format
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y clang-format

    - name: Run clang-format
      run: git ls-files -- '*.cc' '*.hh' '*.hxx' ':!:tcsh/*' | xargs clang-format --dry-run --Werror -style=file
